//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvallio
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceTB
    {
        public int ID { get; set; }
        public string Provider { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
        public string Policy_Number { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public string Plate_Number { get; set; }
    
        public virtual CustomerTB CustomerTB { get; set; }
    }
}
